/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.User;
import Frames.*;import Utility.SingletonConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author admin
 */
public class Authentification extends javax.swing.JFrame  {

    /**
     * Creates new form yupi
     */
    public Authentification() {
        initComponents();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        showpass = new javax.swing.JRadioButton();
        jConnection = new javax.swing.JButton();
        jRefus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 6));
        jPanel2.setLayout(null);

        jLogin.setBackground(new java.awt.Color(153, 153, 153));
        jLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jLogin.setCaretColor(new java.awt.Color(51, 51, 51));
        jLogin.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jLogin);
        jLogin.setBounds(100, 270, 240, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/icon8.PNG"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 260, 60, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/icon12.PNG"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 330, 50, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Authentification");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 190, 190, 40);

        jPass.setBackground(new java.awt.Color(153, 153, 153));
        jPass.setForeground(new java.awt.Color(255, 255, 255));
        jPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassActionPerformed(evt);
            }
        });
        jPanel2.add(jPass);
        jPass.setBounds(100, 330, 240, 40);

        showpass.setBackground(new java.awt.Color(255, 255, 255));
        showpass.setForeground(new java.awt.Color(0, 0, 0));
        showpass.setText("Show Password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel2.add(showpass);
        showpass.setBounds(110, 380, 120, 20);

        jConnection.setBackground(new java.awt.Color(153, 153, 153));
        jConnection.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jConnection.setForeground(new java.awt.Color(0, 0, 0));
        jConnection.setText("Se connecter");
        jConnection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jConnection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jConnectionMouseClicked(evt);
            }
        });
        jConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectionActionPerformed(evt);
            }
        });
        jConnection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jConnectionKeyPressed(evt);
            }
        });
        jPanel2.add(jConnection);
        jConnection.setBounds(260, 430, 130, 30);

        jRefus.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(jRefus);
        jRefus.setBounds(70, 490, 300, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(650, 0, 400, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/vente.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginActionPerformed

    private void jPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassActionPerformed
        // TODO add your handling code here:
        
        
      
    }//GEN-LAST:event_jPassActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
          
       if (showpass.isSelected() == true)
       {
           jPass.setEchoChar((char)0);
       
       }
       else
       {
           jPass.setEchoChar('*');
           
       }
    }//GEN-LAST:event_showpassActionPerformed
 
    private void jConnectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConnectionMouseClicked
        // TODO add your handling code here:
          String login = jLogin.getText();
        String password = jPass.getText();
        User u1 = new User();
      u1=  User.choix_page(login, password);
      
       if (u1.role.equals("A") || u1.role.equals("a"))
       { 
          
           new intA().setVisible(true);
           this.setVisible(false);
          
             
       }
       else if (u1.role.equals("C") || u1.role.equals("c"))
       {
           new initC().setVisible(true);
           this.setVisible(false);
           User uS =new User();
           uS=User.profil_set(u1, u1.id);
           initC.jID.setText(uS.id+"");
              initC.jNomP.setText(uS.nom);
               initC.jPrenomP.setText(uS.prenom);
             initC.jEmailP.setText(uS.email);
               initC.jAdresseP.setText(uS.adresse);
                 initC.jLoginP.setText(uS.login);
                   initC.jPassP.setText(uS.password);
             initC.jNum.setText(uS.num);
           
             
           
       }
       else
       {
          jRefus.setText("Nom de compte ou mot de passe incorect");
           
       }
       
    }//GEN-LAST:event_jConnectionMouseClicked

    private void jConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConnectionActionPerformed

    private void jConnectionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jConnectionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConnectionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jConnection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPass;
    public static javax.swing.JLabel jRefus;
    private javax.swing.JRadioButton showpass;
    // End of variables declaration//GEN-END:variables
}
