/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Frames.Authentification;
import Utility.SingletonConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import Class.*;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class initC extends javax.swing.JFrame {

    /**
     * Creates new form Essaie3
     */
    public initC() {
        initComponents();
        jLabel4.setSize(jPanel3.getSize());
        
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jbtnReturnC = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblCommande = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblAchat = new javax.swing.JTable();
        jbtnReturnA = new javax.swing.JToggleButton();
        jbtnAjoutP = new javax.swing.JToggleButton();
        jbtnVisualiserP = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblPanier = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jbtnReturnP = new javax.swing.JButton();
        jbtnValiderCommande = new javax.swing.JButton();
        jbtnViderPanier = new javax.swing.JButton();
        jbtnsuppProd = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jAdresseP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jNomP = new javax.swing.JTextField();
        jPrenomP = new javax.swing.JTextField();
        jLoginP = new javax.swing.JTextField();
        jPassP = new javax.swing.JTextField();
        jEmailP = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jbtnReturnP1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jmodify = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jID = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/order.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 170, 120, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/commandes.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 110, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/deconnexion.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 460, 100, 90);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/profil.jpg"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 330, 140, 110);

        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 190, 570);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jLabel6.setText("Effectuer un achat");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel4.add(jPanel2);
        jPanel2.setBounds(220, 210, 210, 50);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jLabel5.setText("Mes commandes");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(220, 60, 210, 50);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jLabel15.setText("Mon profil");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel13);
        jPanel13.setBounds(220, 350, 220, 50);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 4));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jPanel6CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 2, 18)); // NOI18N
        jLabel7.setText("Déconnexion");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(220, 490, 220, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/shop.gif"))); // NOI18N
        jPanel4.add(jLabel13);
        jLabel13.setBounds(220, 30, 810, 520);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 1042, 562);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/welcome5.jpg"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabel4ComponentMoved(evt);
            }
        });
        jPanel3.add(jLabel4);
        jLabel4.setBounds(110, 0, 730, 480);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(190, 0, 850, 562);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel8.setText("Mes commandes");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(350, 0, 270, 50);

        jbtnReturnC.setBackground(new java.awt.Color(153, 153, 153));
        jbtnReturnC.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnReturnC.setText("Retour");
        jbtnReturnC.setActionCommand("");
        jbtnReturnC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnReturnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnReturnCMouseClicked(evt);
            }
        });
        jbtnReturnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReturnCActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReturnC);
        jbtnReturnC.setBounds(960, 520, 70, 30);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setLayout(null);

        jtblCommande.setBackground(new java.awt.Color(51, 51, 51));
        jtblCommande.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jtblCommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblCommande.setGridColor(new java.awt.Color(0, 0, 0));
        jtblCommande.setTableHeader(jtblCommande.getTableHeader());
        jtblCommande.setUpdateSelectionOnSort(false);
        jtblCommande.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtblCommandePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jtblCommande);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 790, 430);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(210, 50, 810, 450);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 0, 1042, 562);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel9.setText("Espace d'achat");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(370, 10, 240, 50);

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));

        jtblAchat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblAchat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblAchatMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtblAchat);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel10);
        jPanel10.setBounds(240, 70, 630, 330);

        jbtnReturnA.setBackground(new java.awt.Color(153, 153, 153));
        jbtnReturnA.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnReturnA.setText("Retour");
        jbtnReturnA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnReturnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnReturnAMouseClicked(evt);
            }
        });
        jPanel9.add(jbtnReturnA);
        jbtnReturnA.setBounds(920, 510, 80, 30);

        jbtnAjoutP.setBackground(new java.awt.Color(153, 153, 153));
        jbtnAjoutP.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnAjoutP.setText("Ajouter dans mon panier");
        jbtnAjoutP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        jbtnAjoutP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAjoutPMouseClicked(evt);
            }
        });
        jbtnAjoutP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAjoutPActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnAjoutP);
        jbtnAjoutP.setBounds(250, 440, 210, 40);

        jbtnVisualiserP.setBackground(new java.awt.Color(153, 153, 153));
        jbtnVisualiserP.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnVisualiserP.setText("Visualiser mon panier");
        jbtnVisualiserP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnVisualiserP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnVisualiserPMouseClicked(evt);
            }
        });
        jPanel9.add(jbtnVisualiserP);
        jbtnVisualiserP.setBounds(570, 440, 210, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/Client.jpg"))); // NOI18N
        jPanel9.add(jLabel10);
        jLabel10.setBounds(890, 100, 160, 330);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 0, 1042, 562);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel11.setText("Mon panier");
        jPanel11.add(jLabel11);
        jLabel11.setBounds(500, 20, 200, 40);

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));

        jtblPanier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtblPanier);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel11.add(jPanel12);
        jPanel12.setBounds(430, 80, 600, 330);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/okay2.jpg"))); // NOI18N
        jPanel11.add(jLabel12);
        jLabel12.setBounds(240, 70, 260, 450);

        jbtnReturnP.setBackground(new java.awt.Color(153, 153, 153));
        jbtnReturnP.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jbtnReturnP.setText("Retour");
        jbtnReturnP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnReturnP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnReturnPMouseClicked(evt);
            }
        });
        jbtnReturnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReturnPActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnReturnP);
        jbtnReturnP.setBounds(900, 520, 120, 30);

        jbtnValiderCommande.setBackground(new java.awt.Color(153, 153, 153));
        jbtnValiderCommande.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jbtnValiderCommande.setText("Valider la commande");
        jbtnValiderCommande.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jPanel11.add(jbtnValiderCommande);
        jbtnValiderCommande.setBounds(500, 420, 230, 30);

        jbtnViderPanier.setBackground(new java.awt.Color(153, 153, 153));
        jbtnViderPanier.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jbtnViderPanier.setText("Vider mon panier");
        jbtnViderPanier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnViderPanier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnViderPanierMouseClicked(evt);
            }
        });
        jPanel11.add(jbtnViderPanier);
        jbtnViderPanier.setBounds(750, 420, 200, 30);

        jbtnsuppProd.setBackground(new java.awt.Color(153, 153, 153));
        jbtnsuppProd.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jbtnsuppProd.setText("Supprimer un produit");
        jbtnsuppProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnsuppProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnsuppProdMouseClicked(evt);
            }
        });
        jPanel11.add(jbtnsuppProd);
        jbtnsuppProd.setBounds(610, 470, 220, 30);

        jPanel1.add(jPanel11);
        jPanel11.setBounds(0, 0, 1042, 562);
        jPanel11.getAccessibleContext().setAccessibleName("");

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(1048, 562));
        jPanel14.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel16.setText("Password");
        jPanel14.add(jLabel16);
        jLabel16.setBounds(60, 460, 110, 50);

        jLabel17.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel17.setText("Mon profil");
        jPanel14.add(jLabel17);
        jLabel17.setBounds(320, 20, 210, 50);

        jAdresseP.setBackground(new java.awt.Color(204, 204, 204));
        jAdresseP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jAdresseP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdressePActionPerformed(evt);
            }
        });
        jPanel14.add(jAdresseP);
        jAdresseP.setBounds(170, 290, 300, 50);

        jLabel18.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel18.setText("Nom");
        jPanel14.add(jLabel18);
        jLabel18.setBounds(70, 100, 100, 50);

        jLabel19.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel19.setText("Prénom");
        jPanel14.add(jLabel19);
        jLabel19.setBounds(70, 160, 100, 50);

        jLabel20.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel20.setText("Adresse");
        jPanel14.add(jLabel20);
        jLabel20.setBounds(70, 290, 100, 50);

        jLabel21.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel21.setText("Email");
        jPanel14.add(jLabel21);
        jLabel21.setBounds(70, 220, 100, 50);

        jLabel22.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel22.setText("Login");
        jPanel14.add(jLabel22);
        jLabel22.setBounds(70, 400, 100, 50);

        jNomP.setBackground(new java.awt.Color(204, 204, 204));
        jNomP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jNomP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomPActionPerformed(evt);
            }
        });
        jPanel14.add(jNomP);
        jNomP.setBounds(170, 110, 170, 40);

        jPrenomP.setBackground(new java.awt.Color(204, 204, 204));
        jPrenomP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPrenomP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrenomPActionPerformed(evt);
            }
        });
        jPanel14.add(jPrenomP);
        jPrenomP.setBounds(170, 170, 170, 40);

        jLoginP.setBackground(new java.awt.Color(204, 204, 204));
        jLoginP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jLoginP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginPActionPerformed(evt);
            }
        });
        jPanel14.add(jLoginP);
        jLoginP.setBounds(170, 410, 170, 40);

        jPassP.setBackground(new java.awt.Color(204, 204, 204));
        jPassP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPassP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassPActionPerformed(evt);
            }
        });
        jPanel14.add(jPassP);
        jPassP.setBounds(170, 470, 170, 40);

        jEmailP.setBackground(new java.awt.Color(204, 204, 204));
        jEmailP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jEmailP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailPActionPerformed(evt);
            }
        });
        jPanel14.add(jEmailP);
        jEmailP.setBounds(170, 230, 300, 40);
        jPanel14.add(jLabel23);
        jLabel23.setBounds(660, 290, 0, 0);

        jbtnReturnP1.setBackground(new java.awt.Color(153, 153, 153));
        jbtnReturnP1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jbtnReturnP1.setText("Retour");
        jbtnReturnP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnReturnP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnReturnP1MouseClicked(evt);
            }
        });
        jbtnReturnP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReturnP1ActionPerformed(evt);
            }
        });
        jPanel14.add(jbtnReturnP1);
        jbtnReturnP1.setBounds(680, 510, 150, 30);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/profilH.jpg"))); // NOI18N
        jPanel14.add(jLabel24);
        jLabel24.setBounds(430, 90, 100, 100);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/prodilF.jpg"))); // NOI18N
        jPanel14.add(jLabel25);
        jLabel25.setBounds(530, 80, 130, 110);

        jmodify.setBackground(new java.awt.Color(153, 153, 153));
        jmodify.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jmodify.setText("Modifier");
        jmodify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jmodify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmodifyMouseClicked(evt);
            }
        });
        jmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifyActionPerformed(evt);
            }
        });
        jPanel14.add(jmodify);
        jmodify.setBounds(520, 510, 150, 30);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe Script", 2, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("ID : ");
        jPanel14.add(jLabel26);
        jLabel26.setBounds(670, 120, 40, 30);

        jID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jID.setForeground(new java.awt.Color(0, 0, 0));
        jPanel14.add(jID);
        jID.setBounds(710, 110, 70, 40);

        jLabel27.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel27.setText("Num");
        jPanel14.add(jLabel27);
        jLabel27.setBounds(60, 340, 100, 50);

        jNum.setBackground(new java.awt.Color(204, 204, 204));
        jNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumActionPerformed(evt);
            }
        });
        jPanel14.add(jNum);
        jNum.setBounds(170, 350, 170, 40);

        jPanel1.add(jPanel14);
        jPanel14.setBounds(190, 0, 850, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel2.setVisible(true);
         jPanel5.setVisible(true);
          jPanel6.setVisible(true);
           jPanel7.setVisible(false);
           jPanel11.setVisible(false);
            jPanel14.setVisible(false);
     jPanel5.setBackground(Color.white);
          jPanel5.setForeground(Color.black);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
         
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
         jPanel2.setVisible(true);
         jPanel5.setVisible(true);
          jPanel6.setVisible(true);
           jPanel7.setVisible(false);
           jPanel11.setVisible(false);
             jPanel14.setVisible(false);
          jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.white);
          jPanel2.setForeground(Color.black);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jPanel4.setVisible(true);
        jPanel6.setVisible(true);
          jPanel5.setVisible(true);
            jPanel2.setVisible(true);
             jPanel7.setVisible(false);
              jPanel11.setVisible(false);
             jPanel12.setVisible(false);
               jPanel14.setVisible(false);
            jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.white);
           jPanel6.setForeground(Color.black);
              
    }//GEN-LAST:event_jLabel3MouseEntered
 
    public void Update_tablePClient()
    {
         try{  
        Connection conn= SingletonConnection.getConnection();
        String sql = "SELECT `nom`, `categorie`, `prix` FROM `tbl_produit`";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        jtblAchat.setModel(DbUtils.resultSetToTableModel(rs));
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
          }
        
    }
    
    public void Update_userProd( int id){
        //UPDATE `projetintegre`.`tbl_produit` SET  `idtbl_user` = 5
        
    }
    public void Update_tableP(){
         try{  
        Connection conn= SingletonConnection.getConnection();
        String sql = "SELECT idtbl_produit , nom, categorie ,prix, quantite  FROM projetintegre.tbl_produit";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        jtblAchat.setModel(DbUtils.resultSetToTableModel(rs));
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
          }
    }
    public void Update_tablePanier(){
         try{ 
            int id = Integer.parseInt(jID.getText());
        Connection conn= SingletonConnection.getConnection();
        String sql = "SELECT *  FROM projetintegre.tbl_panier where `idtbl_user` = '"+id+"'";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        jtblPanier.setModel(DbUtils.resultSetToTableModel(rs));
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
          }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jPanel3.setVisible(true);
         jPanel4.setVisible(false);
          jPanel7.setVisible(false);
           jPanel11.setVisible(false);
           jPanel12.setVisible(false);
           jPanel9.setVisible(false);
           jPanel14.setVisible(false);
            jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
           jPanel13.setBackground(Color.getHSBColor(193,27,56));
           jNomP.setEnabled(false);
           jPrenomP.setEnabled(false);
           Update_tableP();
           Update_tablePanier();
         
                   
    }//GEN-LAST:event_formWindowOpened

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
               

    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jbtnReturnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReturnCActionPerformed

        // TODO add your handling code here:
       
    }//GEN-LAST:event_jbtnReturnCActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        
        jPanel4.setVisible(false);
         jPanel7.setVisible(true);
          jPanel3.setVisible(false);
          jPanel9.setVisible(false);
           jPanel11.setVisible(false);
             jPanel14.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel4ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel4ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4ComponentMoved

    private void jtblCommandePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtblCommandePropertyChange
        // TODO add your handling code here:
        jtblCommande.getTableHeader().setOpaque(false);
        jtblCommande.getTableHeader().setBackground(Color.BLACK);

      
    }//GEN-LAST:event_jtblCommandePropertyChange

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
         jPanel9.setVisible(true);
         jPanel4.setVisible(false);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
          jPanel11.setVisible(false);
            jPanel14.setVisible(false);
              try{  int a=0; 
                  int id = Integer.parseInt(jID.getText());
                  System.out.println(id);
        Connection conn= SingletonConnection.getConnection();
        String sql = "UPDATE `projetintegre`.`tbl_produit` SET  `idtbl_user` = '"+id+"'";
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
      a =pst.executeUpdate();
         if (a==1)   {
              Update_tableP();         }
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
                Logger.getLogger(initC.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jbtnReturnAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnReturnAMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(true);
         jPanel9.setVisible(false);
         jPanel4.setVisible(true);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
           jPanel11.setVisible(false);
             jPanel14.setVisible(false);
        
    }//GEN-LAST:event_jbtnReturnAMouseClicked

    private void jbtnReturnCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnReturnCMouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(true);
         jPanel9.setVisible(false);
         jPanel4.setVisible(true);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
           jPanel11.setVisible(false);
             jPanel14.setVisible(false);
    }//GEN-LAST:event_jbtnReturnCMouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        
             jPanel5.setBackground(Color.white);
          jPanel5.setForeground(Color.black);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
             jPanel14.setVisible(false);
        
        
        
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
            jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.white);
          jPanel2.setForeground(Color.black);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
            jPanel11.setVisible(false);
              jPanel14.setVisible(false);
         
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
              jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.white);
           jPanel6.setForeground(Color.black);
         
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
            jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
         jPanel11.setVisible(false);
            
          jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
         jPanel11.setVisible(false);
               jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        new Authentification().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        new Authentification().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel6CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel6CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6CaretPositionChanged

    private void jbtnReturnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReturnPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReturnPActionPerformed

    private void jbtnVisualiserPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnVisualiserPMouseClicked
        // TODO add your handling code here:
        jPanel11.setVisible(true);
         jPanel12.setVisible(true);
         jPanel9.setVisible(false);
         jPanel4.setVisible(false);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
            jPanel14.setVisible(false);
    }//GEN-LAST:event_jbtnVisualiserPMouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        
           jPanel6.setBackground(Color.white);
           jPanel6.setForeground(Color.black);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jbtnReturnPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnReturnPMouseClicked
        // TODO add your handling code here:
         jPanel9.setVisible(true);
         jPanel4.setVisible(false);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
          jPanel11.setVisible(false);
            jPanel14.setVisible(false);
    }//GEN-LAST:event_jbtnReturnPMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        jPanel14.setVisible(true);
           jPanel1.setVisible(true);
         jPanel9.setVisible(false);
         jPanel4.setVisible(false);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
           jPanel11.setVisible(false);

    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        
         jPanel13.setBackground(Color.white);
          jPanel11.setVisible(false);
               jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        // TODO add your handling code here:
        jPanel13.setBackground(Color.white);
          jPanel11.setVisible(false);
               jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        // TODO add your handling code here:
           jPanel13.setBackground(Color.getHSBColor(193,27,56));
          jPanel11.setVisible(false);
               jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jPanel13MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jPanel13.setBackground(Color.white);
          jPanel11.setVisible(false);
               jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
        
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        jPanel13.setBackground(Color.getHSBColor(193,27,56));
          jPanel11.setVisible(false);
               jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jPanel13.setBackground(Color.getHSBColor(193,27,56));
          jPanel11.setVisible(false);
               jPanel5.setBackground(Color.getHSBColor(393,578, 929));
          jPanel5.setForeground(Color.white);
          jPanel2.setBackground(Color.PINK);
          jPanel2.setForeground(Color.white);
           jPanel6.setBackground(Color.getHSBColor(230,38, 68));
           jPanel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
          jPanel14.setVisible(true);
           jPanel1.setVisible(true);
         jPanel9.setVisible(false);
         jPanel4.setVisible(false);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
           jPanel11.setVisible(false);
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jAdressePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdressePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdressePActionPerformed

    private void jNomPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomPActionPerformed

    private void jPrenomPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrenomPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrenomPActionPerformed

    private void jLoginPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginPActionPerformed

    private void jPassPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassPActionPerformed

    private void jEmailPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailPActionPerformed

    private void jbtnReturnP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnReturnP1MouseClicked
        // TODO add your handling code here:
        jPanel14.setVisible(false);
        jPanel1.setVisible(true);
         jPanel9.setVisible(false);
         jPanel4.setVisible(true);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
           jPanel11.setVisible(false);
          
        
    }//GEN-LAST:event_jbtnReturnP1MouseClicked

    private void jbtnReturnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReturnP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReturnP1ActionPerformed

    private void jbtnAjoutPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAjoutPMouseClicked
        // TODO add your handling code here:
  
 int numR=  (int) jtblAchat.getModel().getValueAt(jtblAchat.getSelectedRow(), 0);
 
       Produit p = new Produit();
        
        p = Produit.get_produit(numR);
        
       
        //boolean r =Produit.ajoutProduit_panier(p,numR);
         int idU =Integer.parseInt(jID.getText());
         System.out.println(idU);
        Produit.Ajout_produit_panier(numR, p,idU);
        Update_tableP();
        Update_tablePanier();
        
       
        
        
    }//GEN-LAST:event_jbtnAjoutPMouseClicked

    private void jbtnAjoutPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAjoutPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAjoutPActionPerformed

    private void jtblAchatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblAchatMouseClicked
        // TODO add your handling code here:
             
    }//GEN-LAST:event_jtblAchatMouseClicked

    private void jbtnViderPanierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnViderPanierMouseClicked
        // TODO add your handling code here:
            Panier.suppall_product();
            Update_tablePanier();
    }//GEN-LAST:event_jbtnViderPanierMouseClicked

    private void jbtnsuppProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnsuppProdMouseClicked
        // TODO add your handling code here:
        int numR=  (int) jtblPanier.getModel().getValueAt(jtblPanier.getSelectedRow(),1);
        Panier.suppUn_product(numR);
           Update_tablePanier();
    }//GEN-LAST:event_jbtnsuppProdMouseClicked

    private void jmodifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmodifyMouseClicked
        // TODO add your handling code here:
        
        User u =new User();
       // u.id=Integer.parseInt(jID.getText());
           u.id=Integer.parseInt(jID.getText());
      
      u.num=jNum.getText();
        u.email=jEmailP.getText();
        u.adresse=jAdresseP.getText();
        u.login=jLoginP.getText();
        u.password=jPassP.getText();
      User.Update_Profil(u, u.id);
        User u1= new User();
       u1= User.get_User(u.id);
        
             initC.jEmailP.setText(u1.email);
               initC.jAdresseP.setText(u1.adresse);
                 initC.jLoginP.setText(u1.login);
                   initC.jPassP.setText(u1.password);
                   initC.jID.setText(u1.id+"");
        initC.jNum.setText(u1.num);
        
    }//GEN-LAST:event_jmodifyMouseClicked

    private void jmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmodifyActionPerformed

    private void jNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
       jPanel9.setVisible(true);
         jPanel4.setVisible(false);
         jPanel7.setVisible(false);
          jPanel3.setVisible(false);
          jPanel11.setVisible(false);
            jPanel14.setVisible(false);
              try{  int a=0; 
                  int id = Integer.parseInt(jID.getText());
                  System.out.println(id);
        Connection conn= SingletonConnection.getConnection();
        String sql = "UPDATE `projetintegre`.`tbl_produit` SET  `idtbl_user` = '"+id+"'";
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
      a =pst.executeUpdate();
         if (a==1)   {
              Update_tableP();         }
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
                Logger.getLogger(initC.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(initC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(initC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(initC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(initC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new initC().setVisible(true);
          

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField jAdresseP;
    public static javax.swing.JTextField jEmailP;
    public static javax.swing.JLabel jID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jLoginP;
    public static javax.swing.JTextField jNomP;
    public static javax.swing.JTextField jNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JTextField jPassP;
    public static javax.swing.JTextField jPrenomP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jbtnAjoutP;
    private javax.swing.JToggleButton jbtnReturnA;
    private javax.swing.JButton jbtnReturnC;
    private javax.swing.JButton jbtnReturnP;
    private javax.swing.JButton jbtnReturnP1;
    private javax.swing.JButton jbtnValiderCommande;
    private javax.swing.JButton jbtnViderPanier;
    private javax.swing.JToggleButton jbtnVisualiserP;
    private javax.swing.JButton jbtnsuppProd;
    private javax.swing.JButton jmodify;
    public static javax.swing.JTable jtblAchat;
    private static javax.swing.JTable jtblCommande;
    private javax.swing.JTable jtblPanier;
    // End of variables declaration//GEN-END:variables
}
