/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Class.Fournisseur;
import Class.Produit;
import Class.User;
import Utility.SingletonConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author admin
 */
public class intA extends javax.swing.JFrame {

    /**
     * Creates new form intA
     */
    public intA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLoginC = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblGestionC = new javax.swing.JTable();
        jbtnListerC = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jNomC = new javax.swing.JTextField();
        jPrenomC = new javax.swing.JTextField();
        jAdressC = new javax.swing.JTextField();
        jEmailC = new javax.swing.JTextField();
        jNumC = new javax.swing.JTextField();
        jbtnAjoutC = new javax.swing.JButton();
        jbtnSuppC = new javax.swing.JButton();
        jbtnModifC = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPassC1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jFiltrerC = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jCategorieP = new javax.swing.JTextField();
        jQuantiteP = new javax.swing.JTextField();
        jNomP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblGestionP = new javax.swing.JTable();
        jbtnSuppP = new javax.swing.JButton();
        jbtnModifierP = new javax.swing.JButton();
        jbtnAjoutP = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jbtnListerP = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPrixP = new javax.swing.JTextField();
        jFiltrerP = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbtnSuppF = new javax.swing.JButton();
        jbtnModifierF = new javax.swing.JButton();
        jbtnAjoutF = new javax.swing.JButton();
        jbtnListerF = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblF = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jNomF = new javax.swing.JTextField();
        jNumF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        JprenomF = new javax.swing.JTextField();
        jAdresseF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jEmailF = new javax.swing.JTextField();
        jFiltrerF = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1038, 560));
        jPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel8.setText("Gestion des produits");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel2);
        jPanel2.setBounds(590, 190, 240, 60);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel7.setText("Gestion des comptes clients");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel3);
        jPanel3.setBounds(590, 50, 240, 60);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel10.setText("Déconnexion");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel4);
        jPanel4.setBounds(590, 460, 246, 74);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel9.setText("Gestion des fournisseurs");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel5);
        jPanel5.setBounds(590, 330, 240, 74);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Espace admin");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(20, 20, 240, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/adminn.gif"))); // NOI18N
        jPanel6.add(jLabel11);
        jLabel11.setBounds(110, 90, 470, 330);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 850, 560);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/deconnexion.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(890, 440, 120, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/Gfournisseurs.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(890, 300, 120, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/Gcomptes.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(890, 20, 120, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/GCommandes.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(900, 150, 120, 120);

        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(850, 0, 190, 570);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);
        jPanel9.add(jLabel32);
        jLabel32.setBounds(135, 237, 0, 0);

        jLabel34.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel34.setText("Gestion des clients");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(10, 50, 250, 40);

        jLabel35.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel35.setText("Adresse");
        jPanel9.add(jLabel35);
        jLabel35.setBounds(10, 240, 80, 40);

        jLabel24.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel24.setText("Num");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(10, 340, 80, 40);

        jLabel18.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel18.setText("Login");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(10, 390, 150, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel2.setText("Nom");
        jPanel9.add(jLabel2);
        jLabel2.setBounds(10, 140, 90, 40);

        jLabel25.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel25.setText("Prénom");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(10, 190, 80, 40);
        jPanel9.add(jLabel23);
        jLabel23.setBounds(700, 430, 29, 16);

        jLoginC.setBackground(new java.awt.Color(204, 204, 204));
        jLoginC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jLoginC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginCActionPerformed(evt);
            }
        });
        jPanel9.add(jLoginC);
        jLoginC.setBounds(140, 390, 180, 40);

        jLabel36.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel36.setText("Email");
        jPanel9.add(jLabel36);
        jLabel36.setBounds(10, 290, 80, 40);

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));

        jtblGestionC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prenom", "Address", "Email", "Mot de passe", "Num tel"
            }
        ));
        jtblGestionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblGestionCMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtblGestionC);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(jPanel10);
        jPanel10.setBounds(330, 160, 510, 340);

        jbtnListerC.setBackground(new java.awt.Color(153, 153, 153));
        jbtnListerC.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnListerC.setText("Vider les champs");
        jbtnListerC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnListerC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnListerCMouseClicked(evt);
            }
        });
        jbtnListerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListerCActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnListerC);
        jbtnListerC.setBounds(10, 500, 140, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/clientG.jpg"))); // NOI18N
        jPanel9.add(jLabel12);
        jLabel12.setBounds(250, 10, 130, 100);

        jNomC.setBackground(new java.awt.Color(204, 204, 204));
        jNomC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel9.add(jNomC);
        jNomC.setBounds(140, 140, 180, 40);

        jPrenomC.setBackground(new java.awt.Color(204, 204, 204));
        jPrenomC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel9.add(jPrenomC);
        jPrenomC.setBounds(140, 190, 180, 40);

        jAdressC.setBackground(new java.awt.Color(204, 204, 204));
        jAdressC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel9.add(jAdressC);
        jAdressC.setBounds(140, 240, 180, 40);

        jEmailC.setBackground(new java.awt.Color(204, 204, 204));
        jEmailC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel9.add(jEmailC);
        jEmailC.setBounds(140, 290, 180, 40);

        jNumC.setBackground(new java.awt.Color(204, 204, 204));
        jNumC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jNumC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumCActionPerformed(evt);
            }
        });
        jPanel9.add(jNumC);
        jNumC.setBounds(140, 340, 180, 40);

        jbtnAjoutC.setBackground(new java.awt.Color(153, 153, 153));
        jbtnAjoutC.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnAjoutC.setText("Ajouter");
        jbtnAjoutC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnAjoutC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAjoutCMouseClicked(evt);
            }
        });
        jPanel9.add(jbtnAjoutC);
        jbtnAjoutC.setBounds(340, 520, 100, 30);

        jbtnSuppC.setBackground(new java.awt.Color(153, 153, 153));
        jbtnSuppC.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnSuppC.setText("Supprimer");
        jbtnSuppC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnSuppC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSuppCMouseClicked(evt);
            }
        });
        jbtnSuppC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuppCActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnSuppC);
        jbtnSuppC.setBounds(580, 520, 110, 30);

        jbtnModifC.setBackground(new java.awt.Color(153, 153, 153));
        jbtnModifC.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnModifC.setText("Modifier");
        jbtnModifC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnModifC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnModifCMouseClicked(evt);
            }
        });
        jbtnModifC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifCActionPerformed(evt);
            }
        });
        jPanel9.add(jbtnModifC);
        jbtnModifC.setBounds(480, 520, 80, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/retour2.jpg"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel20);
        jLabel20.setBounds(790, 500, 47, 50);

        jPassC1.setBackground(new java.awt.Color(204, 204, 204));
        jPassC1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPassC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassC1ActionPerformed(evt);
            }
        });
        jPanel9.add(jPassC1);
        jPassC1.setBounds(140, 440, 180, 40);

        jLabel33.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel33.setText("Mot de passe");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(10, 440, 150, 40);

        jFiltrerC.setBackground(new java.awt.Color(204, 204, 204));
        jFiltrerC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jFiltrerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFiltrerCActionPerformed(evt);
            }
        });
        jFiltrerC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFiltrerCKeyTyped(evt);
            }
        });
        jPanel9.add(jFiltrerC);
        jFiltrerC.setBounds(590, 120, 180, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox2);
        jComboBox2.setBounds(500, 120, 70, 30);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 0, 850, 560);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel37.setText("Gestion des produits");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(10, 60, 250, 40);

        jCategorieP.setBackground(new java.awt.Color(204, 204, 204));
        jCategorieP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel7.add(jCategorieP);
        jCategorieP.setBounds(140, 240, 180, 40);

        jQuantiteP.setBackground(new java.awt.Color(204, 204, 204));
        jQuantiteP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel7.add(jQuantiteP);
        jQuantiteP.setBounds(140, 300, 180, 40);

        jNomP.setBackground(new java.awt.Color(204, 204, 204));
        jNomP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel7.add(jNomP);
        jNomP.setBounds(140, 180, 180, 40);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel13.setText("Catégorie");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(10, 240, 90, 40);

        jLabel14.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel14.setText("Quantité");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(10, 300, 90, 40);

        jLabel15.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel15.setText("Prix");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(20, 360, 90, 40);

        jLabel16.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel16.setText("Nom");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(20, 180, 90, 40);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        jtblGestionP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblGestionP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblGestionPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblGestionP);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel8);
        jPanel8.setBounds(350, 160, 500, 320);

        jbtnSuppP.setBackground(new java.awt.Color(153, 153, 153));
        jbtnSuppP.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnSuppP.setText("Supprimer");
        jbtnSuppP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnSuppP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSuppPMouseClicked(evt);
            }
        });
        jbtnSuppP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuppPActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnSuppP);
        jbtnSuppP.setBounds(620, 510, 110, 30);

        jbtnModifierP.setBackground(new java.awt.Color(153, 153, 153));
        jbtnModifierP.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnModifierP.setText("Modifier");
        jbtnModifierP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnModifierP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnModifierPMouseClicked(evt);
            }
        });
        jbtnModifierP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifierPActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnModifierP);
        jbtnModifierP.setBounds(510, 510, 80, 30);

        jbtnAjoutP.setBackground(new java.awt.Color(153, 153, 153));
        jbtnAjoutP.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnAjoutP.setText("Ajouter");
        jbtnAjoutP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnAjoutP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAjoutPMouseClicked(evt);
            }
        });
        jPanel7.add(jbtnAjoutP);
        jbtnAjoutP.setBounds(380, 510, 100, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/prodG.jpg"))); // NOI18N
        jPanel7.add(jLabel17);
        jLabel17.setBounds(290, 20, 120, 90);

        jbtnListerP.setBackground(new java.awt.Color(153, 153, 153));
        jbtnListerP.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnListerP.setText("Vider les champs");
        jbtnListerP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnListerP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnListerPMouseClicked(evt);
            }
        });
        jbtnListerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListerPActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnListerP);
        jbtnListerP.setBounds(20, 420, 140, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/retour2.jpg"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel19);
        jLabel19.setBounds(790, 500, 47, 50);

        jPrixP.setBackground(new java.awt.Color(204, 204, 204));
        jPrixP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel7.add(jPrixP);
        jPrixP.setBounds(140, 360, 180, 40);

        jFiltrerP.setBackground(new java.awt.Color(204, 204, 204));
        jFiltrerP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jFiltrerP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFiltrerPKeyTyped(evt);
            }
        });
        jPanel7.add(jFiltrerP);
        jFiltrerP.setBounds(580, 120, 160, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(jComboBox1);
        jComboBox1.setBounds(490, 120, 70, 30);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 0, 850, 560);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel38.setText("Gestion des fournisseurs");
        jPanel11.add(jLabel38);
        jLabel38.setBounds(10, 40, 350, 40);

        jLabel21.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel21.setText("Num");
        jPanel11.add(jLabel21);
        jLabel21.setBounds(10, 440, 90, 40);

        jLabel22.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel22.setText("Prenom");
        jPanel11.add(jLabel22);
        jLabel22.setBounds(10, 220, 130, 40);

        jbtnSuppF.setBackground(new java.awt.Color(153, 153, 153));
        jbtnSuppF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnSuppF.setText("Supprimer");
        jbtnSuppF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnSuppF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSuppFMouseClicked(evt);
            }
        });
        jbtnSuppF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuppFActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnSuppF);
        jbtnSuppF.setBounds(640, 510, 110, 30);

        jbtnModifierF.setBackground(new java.awt.Color(153, 153, 153));
        jbtnModifierF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnModifierF.setText("Modifier");
        jbtnModifierF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnModifierF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnModifierFMouseClicked(evt);
            }
        });
        jbtnModifierF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModifierFActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnModifierF);
        jbtnModifierF.setBounds(520, 510, 80, 30);

        jbtnAjoutF.setBackground(new java.awt.Color(153, 153, 153));
        jbtnAjoutF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnAjoutF.setText("Ajouter");
        jbtnAjoutF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnAjoutF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAjoutFMouseClicked(evt);
            }
        });
        jPanel11.add(jbtnAjoutF);
        jbtnAjoutF.setBounds(380, 510, 100, 30);

        jbtnListerF.setBackground(new java.awt.Color(153, 153, 153));
        jbtnListerF.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jbtnListerF.setText("Vider les champs");
        jbtnListerF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnListerF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnListerFMouseClicked(evt);
            }
        });
        jbtnListerF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListerFActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnListerF);
        jbtnListerF.setBounds(20, 500, 150, 30);

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));

        jtblF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblFMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtblF);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.add(jPanel12);
        jPanel12.setBounds(340, 170, 500, 320);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/retour2.jpg"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel26);
        jLabel26.setBounds(790, 500, 47, 50);

        jNomF.setBackground(new java.awt.Color(204, 204, 204));
        jNomF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel11.add(jNomF);
        jNomF.setBounds(130, 160, 180, 40);

        jNumF.setBackground(new java.awt.Color(204, 204, 204));
        jNumF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel11.add(jNumF);
        jNumF.setBounds(130, 440, 180, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/images/fourni.jpg"))); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel11.add(jLabel27);
        jLabel27.setBounds(350, 10, 100, 100);

        jLabel29.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel29.setText("Nom");
        jPanel11.add(jLabel29);
        jLabel29.setBounds(10, 160, 130, 40);

        JprenomF.setBackground(new java.awt.Color(204, 204, 204));
        JprenomF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel11.add(JprenomF);
        JprenomF.setBounds(130, 230, 180, 40);

        jAdresseF.setBackground(new java.awt.Color(204, 204, 204));
        jAdresseF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel11.add(jAdresseF);
        jAdresseF.setBounds(130, 300, 180, 40);

        jLabel30.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel30.setText("Adresse");
        jPanel11.add(jLabel30);
        jLabel30.setBounds(10, 300, 90, 40);

        jLabel31.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel31.setText("Email");
        jPanel11.add(jLabel31);
        jLabel31.setBounds(10, 370, 90, 40);

        jEmailF.setBackground(new java.awt.Color(204, 204, 204));
        jEmailF.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        jPanel11.add(jEmailF);
        jEmailF.setBounds(130, 370, 180, 40);

        jFiltrerF.setBackground(new java.awt.Color(204, 204, 204));
        jFiltrerF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jFiltrerF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFiltrerFKeyTyped(evt);
            }
        });
        jPanel11.add(jFiltrerF);
        jFiltrerF.setBounds(610, 130, 180, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel11.add(jComboBox3);
        jComboBox3.setBounds(530, 130, 70, 30);

        jPanel1.add(jPanel11);
        jPanel11.setBounds(0, 0, 850, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(Color.white);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        jPanel7.setVisible(true);
          jPanel9.setVisible(false);
          jPanel6.setVisible(false); 
          jPanel11.setVisible(false);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        jPanel5.setBackground(Color.white);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered

          jPanel4.setBackground(Color.white);      
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
                jPanel2.setBackground(Color.white);

    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
                jPanel3.setBackground(Color.GRAY);

    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
         jPanel2.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
         jPanel5.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
         jPanel4.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here
      
        jPanel6.setVisible(false);
            jPanel9.setVisible(true); 
           jPanel7.setVisible(false);
           jPanel11.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jbtnModifCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnModifCActionPerformed

    private void jbtnSuppCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuppCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSuppCActionPerformed

    private void jbtnListerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListerCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnListerCActionPerformed
public  void Update_tableGP(){
         try{  
        Connection conn= SingletonConnection.getConnection();
        String sql = "SELECT * FROM projetintegre.tbl_produit";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        jtblGestionP.setModel(DbUtils.resultSetToTableModel(rs));
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
          }
    }
public void Update_tableGC(){
         try{  
        Connection conn= SingletonConnection.getConnection();
        String sql = "SELECT * FROM projetintegre.tbl_user";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        jtblGestionC.setModel(DbUtils.resultSetToTableModel(rs));
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
          }
    }
public void Update_tableF(){
         try{  
        Connection conn= SingletonConnection.getConnection();
        String sql = "SELECT * FROM projetintegre.tbl_fournisseur";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
        jtblF.setModel(DbUtils.resultSetToTableModel(rs));
      
         }
      catch(SQLException ex){
              JOptionPane.showMessageDialog(null, "Prolbleme lors de l'affichage  !!"); 
          }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jPanel6.setVisible(true);
        jPanel7.setVisible(false);   
         jPanel9.setVisible(false);
         jPanel11.setVisible(false);
          Update_tableGP();
          Update_tableGC();
          Update_tableF();
    }//GEN-LAST:event_formWindowOpened

    private void jNumCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumCActionPerformed

    private void jLoginCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLoginCActionPerformed

    private void jbtnSuppPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuppPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSuppPActionPerformed

    private void jbtnModifierPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifierPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnModifierPActionPerformed

    private void jbtnListerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListerPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnListerPActionPerformed

    private void jbtnSuppFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuppFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSuppFActionPerformed

    private void jbtnModifierFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModifierFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnModifierFActionPerformed

    private void jbtnListerFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListerFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnListerFActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        jPanel11.setVisible(true);
        jPanel9.setVisible(false);
        jPanel7.setVisible(false);
        jPanel6.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
         jPanel6.setVisible(true);
        jPanel7.setVisible(false);   
         jPanel9.setVisible(false);
         jPanel11.setVisible(false);
          
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
         jPanel6.setVisible(true);
        jPanel7.setVisible(false);   
         jPanel9.setVisible(false);
         jPanel11.setVisible(false);
          
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
         jPanel6.setVisible(true);
        jPanel7.setVisible(false);   
         jPanel9.setVisible(false);
         jPanel11.setVisible(false);
          
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jPassC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassC1ActionPerformed

    private void jbtnAjoutPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAjoutPMouseClicked
        // TODO add your handling code here:
        Produit p = new Produit();
        p.nom=jNomP.getText();
        p.categorie=jCategorieP.getText();
        p.quantite=Integer.parseInt(jQuantiteP.getText());
        p.prix=Double.parseDouble(jPrixP.getText());
        
         try {
            boolean a= Produit.creatProduit(p);
           Update_tableGP();
            jNomP.setText("");
        jCategorieP.setText("");
        jQuantiteP.setText("");
        jPrixP.setText("");
            //Participant.getAllParticipant();
        } catch (SQLException ex) {
            Logger.getLogger(intA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jbtnAjoutPMouseClicked

    private void jbtnAjoutCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAjoutCMouseClicked
        // TODO add your handling code here:
        User C =new User();
        C.nom=jNomC.getText();
        C.prenom=jPrenomC.getText();
        C.num=jNumC.getText();
        C.adresse=jAdressC.getText();
        C.email=jEmailC.getText();
        C.login=jLoginC.getText();
        C.password=jPassC1.getText();
        try {
            boolean a= User.creatClient(C);
           Update_tableGC();
            jNomC.setText("");
         jPrenomC.setText("");
         jNumC.setText("");
         jAdressC.setText("");
         jEmailC.setText("");
         jLoginC.setText("");
         jPassC1.setText("");
            //Participant.getAllParticipant();
        } catch (SQLException ex) {
            Logger.getLogger(intA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jbtnAjoutCMouseClicked

    private void jbtnAjoutFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAjoutFMouseClicked
        // TODO add your handling code here:
        Fournisseur F =new Fournisseur();
        F.nom=jNomF.getText();
        F.prenom=JprenomF.getText();
        F.num=jNumF.getText();
        F.email=jEmailF.getText();
        F.adresse=jAdresseF.getText();
         try {
            boolean a= Fournisseur.creatFournisseur(F);
           Update_tableF();
            jNomF.setText("");
           JprenomF.setText("");
         jAdresseF.setText("");
         jEmailF.setText("");
          jNumF.setText("");
            //Participant.getAllParticipant();
        } catch (SQLException ex) {
            Logger.getLogger(intA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnAjoutFMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Authentification().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
        new Authentification().setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jbtnSuppCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSuppCMouseClicked
        // TODO add your handling code here:
         int numR=(int) jtblGestionC.getModel().getValueAt(jtblGestionC.getSelectedRow(), 0);
         boolean a = User.Supprimer_Client(numR);
         Update_tableGC();
          jNomC.setText("");
         jPrenomC.setText("");
         jNumC.setText("");
         jAdressC.setText("");
         jEmailC.setText("");
         jLoginC.setText("");
         jPassC1.setText("");
    }//GEN-LAST:event_jbtnSuppCMouseClicked

    private void jbtnSuppPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSuppPMouseClicked
        // TODO add your handling code here:
          int numR=(int) jtblGestionP.getModel().getValueAt(jtblGestionP.getSelectedRow(), 0);
         boolean a = Produit.Supprimer_Produit(numR);
         Update_tableGP();
         jNomP.setText("");
        jCategorieP.setText("");
        jQuantiteP.setText("");
        jPrixP.setText("");
    }//GEN-LAST:event_jbtnSuppPMouseClicked

    private void jbtnSuppFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSuppFMouseClicked
        // TODO add your handling code here:
          int numR=(int) jtblF.getModel().getValueAt(jtblF.getSelectedRow(), 0);
         boolean a = Fournisseur.Supprimer_Fournisseur(numR);
         Update_tableF();
          jNomF.setText("");
           JprenomF.setText("");
         jAdresseF.setText("");
         jEmailF.setText("");
          jNumF.setText("");
    }//GEN-LAST:event_jbtnSuppFMouseClicked

    private void jbtnModifCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnModifCMouseClicked
        // TODO add your handling code here:
      User c = new User();
       int numR=(int) jtblGestionC.getModel().getValueAt(jtblGestionC.getSelectedRow(), 0);
          c.nom=jNomC.getText();
        c.prenom=jPrenomC.getText();
        c.num=jNumC.getText();
        c.adresse=jAdressC.getText();
        c.email=jEmailC.getText();
        c.login=jLoginC.getText();
        c.password=jPassC1.getText();
        boolean a =User.ModifyUser(c,numR);
        Update_tableGC();
        jNomC.setText("");
         jPrenomC.setText("");
         jNumC.setText("");
         jAdressC.setText("");
         jEmailC.setText("");
         jLoginC.setText("");
         jPassC1.setText("");
       
        
    }//GEN-LAST:event_jbtnModifCMouseClicked

    private void jbtnModifierPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnModifierPMouseClicked
        // TODO add your handling code here:
           Produit p = new Produit();
           int numR=(int) jtblGestionP.getModel().getValueAt(jtblGestionP.getSelectedRow(), 0);
        p.nom=jNomP.getText();
        p.categorie=jCategorieP.getText();
        p.quantite=Integer.parseInt(jQuantiteP.getText());
        p.prix=Double.parseDouble(jPrixP.getText());
        
        boolean a= Produit.ModifyProduit(p,numR);
        Update_tableGP();
        //Participant.getAllParticipant();
        jNomP.setText("");
        jCategorieP.setText("");
        jQuantiteP.setText("");
        jPrixP.setText("");
    }//GEN-LAST:event_jbtnModifierPMouseClicked

    private void jbtnListerPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnListerPMouseClicked
        // TODO add your handling code here:
         jNomP.setText("");
        jCategorieP.setText("");
        jQuantiteP.setText("");
        jPrixP.setText("");
        
    }//GEN-LAST:event_jbtnListerPMouseClicked

    private void jtblGestionPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblGestionPMouseClicked
        // TODO add your handling code here:
        int numR=(int) jtblGestionP.getModel().getValueAt(jtblGestionP.getSelectedRow(), 0);
         Produit p2 = new Produit();
        p2=Produit.get_produit(numR);
        jNomP.setText(p2.nom);
        jCategorieP.setText(p2.categorie);
        jQuantiteP.setText(p2.quantite+"");
        jPrixP.setText(p2.prix+"");
    }//GEN-LAST:event_jtblGestionPMouseClicked

    private void jtblGestionCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblGestionCMouseClicked
        // TODO add your handling code here:
         int numR=(int) jtblGestionC.getModel().getValueAt(jtblGestionC.getSelectedRow(), 0);
         User C2= new User();
         C2=User.get_User(numR);
         jNomC.setText(C2.nom);
         jPrenomC.setText(C2.prenom);
         jNumC.setText(C2.num);
         jAdressC.setText(C2.adresse);
         jEmailC.setText(C2.email);
         jLoginC.setText(C2.login);
         jPassC1.setText(C2.password);
    }//GEN-LAST:event_jtblGestionCMouseClicked

    private void jbtnListerCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnListerCMouseClicked
        // TODO add your handling code here:
         jNomC.setText("");
         jPrenomC.setText("");
         jNumC.setText("");
         jAdressC.setText("");
         jEmailC.setText("");
         jLoginC.setText("");
         jPassC1.setText("");
    }//GEN-LAST:event_jbtnListerCMouseClicked

    private void jtblFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblFMouseClicked
        // TODO add your handling code here:
            int numR=(int) jtblF.getModel().getValueAt(jtblF.getSelectedRow(), 0);
          Fournisseur f = new Fournisseur();
          f=Fournisseur.get_Fournisseur(numR);
          
          jNomF.setText(f.nom);
         JprenomF.setText(f.prenom);
         jAdresseF.setText(f.adresse);
         jEmailF.setText(f.email);
        jNumF.setText(f.num);
          
    }//GEN-LAST:event_jtblFMouseClicked

    private void jbtnModifierFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnModifierFMouseClicked
        // TODO add your handling code here:
        Fournisseur f =new Fournisseur();
          int numR=(int) jtblF.getModel().getValueAt(jtblF.getSelectedRow(), 0);
          f.nom=jNomF.getText();
        f.prenom=JprenomF.getText();
       f.adresse=jAdresseF.getText();
        f.email=jEmailF.getText();
        f.num=jNumF.getText();
        
        boolean a =Fournisseur.ModifyFournisseur(f, numR);
        Update_tableF();
         jNomF.setText("");
         JprenomF.setText("");
         jAdresseF.setText("");
         jEmailF.setText("");
          jNumF.setText("");
         
        
    }//GEN-LAST:event_jbtnModifierFMouseClicked

    private void jbtnListerFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnListerFMouseClicked
        // TODO add your handling code here:
         jNomF.setText("");
           JprenomF.setText("");
         jAdresseF.setText("");
         jEmailF.setText("");
          jNumF.setText("");
    }//GEN-LAST:event_jbtnListerFMouseClicked
    
    
    
    private void jFiltrerPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFiltrerPKeyTyped
        try {
         
            // TODO add your handling code here:
            String keyword = jFiltrerP.getText();
            Connection cnx = SingletonConnection.getConnection();
            String requete ="SELECT * FROM `tbl_produit` WHERE `nom` LIKE '%"+keyword+"%'";
            PreparedStatement ps = cnx.prepareStatement(requete);
            ResultSet rs = ps.executeQuery(requete);
            jtblGestionP.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(intA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jFiltrerPKeyTyped

    private void jFiltrerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFiltrerCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFiltrerCActionPerformed

    private void jFiltrerCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFiltrerCKeyTyped
        // TODO add your handling code here:
           try {
         
            // TODO add your handling code here:
            String keyword = jFiltrerC.getText();
            Connection cnx = SingletonConnection.getConnection();
            String requete ="SELECT * FROM `tbl_user` WHERE `nom` LIKE '%"+keyword+"%'";
            PreparedStatement ps = cnx.prepareStatement(requete);
            ResultSet rs = ps.executeQuery(requete);
            jtblGestionC.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(intA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jFiltrerCKeyTyped

    private void jFiltrerFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFiltrerFKeyTyped
        // TODO add your handling code here:
           try {
         
            // TODO add your handling code here:
            String keyword = jFiltrerF.getText();
            Connection cnx = SingletonConnection.getConnection();
            String requete ="SELECT * FROM `tbl_fournisseur` WHERE `nom` LIKE '%"+keyword+"%'";
            PreparedStatement ps = cnx.prepareStatement(requete);
            ResultSet rs = ps.executeQuery(requete);
            jtblF.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(intA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jFiltrerFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JprenomF;
    private javax.swing.JTextField jAdressC;
    private javax.swing.JTextField jAdresseF;
    private javax.swing.JTextField jCategorieP;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JTextField jEmailC;
    private javax.swing.JTextField jEmailF;
    private javax.swing.JTextField jFiltrerC;
    private javax.swing.JTextField jFiltrerF;
    private javax.swing.JTextField jFiltrerP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLoginC;
    private javax.swing.JTextField jNomC;
    private javax.swing.JTextField jNomF;
    private javax.swing.JTextField jNomP;
    private javax.swing.JTextField jNumC;
    private javax.swing.JTextField jNumF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jPassC1;
    private javax.swing.JTextField jPrenomC;
    private javax.swing.JTextField jPrixP;
    private javax.swing.JTextField jQuantiteP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton jbtnAjoutC;
    private javax.swing.JButton jbtnAjoutF;
    private javax.swing.JButton jbtnAjoutP;
    private javax.swing.JButton jbtnListerC;
    private javax.swing.JButton jbtnListerF;
    private javax.swing.JButton jbtnListerP;
    private javax.swing.JButton jbtnModifC;
    private javax.swing.JButton jbtnModifierF;
    private javax.swing.JButton jbtnModifierP;
    private javax.swing.JButton jbtnSuppC;
    private javax.swing.JButton jbtnSuppF;
    private javax.swing.JButton jbtnSuppP;
    private javax.swing.JTable jtblF;
    private javax.swing.JTable jtblGestionC;
    private javax.swing.JTable jtblGestionP;
    // End of variables declaration//GEN-END:variables
}
